# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='pai',
        ),
        migrations.RemoveField(
            model_name='depoimentos',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='destinatario',
        ),
        migrations.DeleteModel(
            name='TipoDepoimentos',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Depoimentos',
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
