# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_auto_20180816_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimentos',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comum.TipoDepoimentos'),
        ),
    ]
