# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_depoimentos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentos',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
