# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_auto_20180817_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimentos',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100),
            preserve_default=False,
        ),
    ]
